version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot_password" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: $SPRING_DATASOURCE_USERNAME
      SPRING_DATASOURCE_PASSWORD: $SPRING_DATASOURCE_PASSWORD
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
